verslag: main.tex
	pdflatex main
	bibtex main
	pdflatex main
	pdflatex main
	# mv main.pdf verslag.pdf
	-rm -f *.acr
	-rm -f *.acn
	-rm -f *.aux
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.glo
	-rm -f *.hst
	-rm -f *.idx
	-rm -f *.ist
	-rm -f *.lof
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.ver
	-rm -f *.ilg
	-rm -f *.ind
	-rm -f *.fls
	-rm -f *.fdb_latexmk
	-rm -f Sources/*.aux
